version: '3'

services:

  app:
    build:
      context: .
    ports:
    - 8080:8080
    environment:
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_HOST: mongo
    container_name: app
    networks:
      - app-net
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    ports:
    - 27017:27017
    container_name: mongo
    hostname: mongo
    volumes:
    - ./data/clinic:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - app-net

  jaeger:
    image: jaegertracing/all-in-one:1.22
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - app-net

networks:
  app-net:
    driver: bridge